(Read fdb-environment.properties if present staring sqlline) (REL-474)
Add doc. on setting fdb env variables before launching CLI (I tried
modifying startup script to ensure fdb client cluster config and
shared lib are available and make sense but the combinations became
profuse and the constraint likely to frustrate so lets try detailed
doc. first).

Fix some spew when cli is launched w/o first building.

Signed-off-by: yhatem

diff --git a/fdb-relational-cli/bin/sqlline b/fdb-relational-cli/bin/sqlline
--- a/fdb-relational-cli/bin/sqlline
+++ b/fdb-relational-cli/bin/sqlline
@@ -44,9 +44,9 @@ done
 
 APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
 APP_NAME=`basename "$0"`
-
 target="${APP_HOME}/.out/install/${APP_NAME}/bin/${APP_NAME}"
 if [ ! -x "${target}" ]; then
-  echo "Please build before running this script (Failed to find executable script at ${target})"
+  echo "Please build Relational before running this script (Failed to find executable script at ${target})"
+  exit 1
 fi
 exec "${target}" "$@"
